using System.Net;
using MovieConnections.Data.Models;

namespace MovieConnections.Data.Entities.SupplementaryModels {
    public interface ICustomRoute : IEntity
    {
        string Url { get; set; }
        string SeoTitle { get; set; }
        string MetaKeyword { get; set; }
        string MetaDescription { get; set; }
        int ContentId { get; set; }
        bool IsAutoGenerated { get; set; }
        HttpStatusCode HttpStatusCode { get; set; }
        PredefinedPage PredefinedPage { get; set; }
    }

    public class CustomRoute : ICustomRoute{
        public int Id { get; set; }
        public string Url { get; set; }
        public string SeoTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public int ContentId { get; set; }
        public bool IsAutoGenerated { get; set; }
        public HttpStatusCode HttpStatusCode { get; set; }
        public PredefinedPage PredefinedPage { get; set; }
    }
}