using System.Net;
using MovieConnections.Core.Model;
using MovieConnections.Data.Entities;
using MovieConnections.Data.Models;

namespace MovieConnections.Core.EntityParams {
    public class CityParams : ICity, IHasCustomRoute, ICulturedEntityParams
    {
        public int Id { get; set; }
        public int BaseEntityId { get; set; }
        public int RelatedEntityId { get; set; }
        public string Name { get; set; }
        public bool IsOverpopulated { get; set; }

        public int CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
        public UserTypes UserType { get; set; }

        public string Url { get; set; }
        public string SeoTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public int ContentId { get; set; }
        public bool IsAutoGenerated { get; set; }
        public HttpStatusCode HttpStatusCode { get; set; }
        public PredefinedPage PredefinedPage { get; set; }
        public string[] UrlParts { get; set; }

        public Status Status { get; set; }
    }
}